# Shuffling Tensors

Shuffling a tensor is necessary when trying to unorder a dataset to help the model learn patterns from varied examples. Take for example a dataset with 15,0000 rows or examples and the first 10,000 examples  relate to `ramen` and the last 5,000 examples relat to `spaghetti`, Training a model with this order will not yield favorable results with the model learning ramen patterns more than spaghetti.

**tf.random.shuffle**

In [2]:
import tensorflow as tf

# first we will create a random tensor
generator = tf.random.Generator.from_seed(42)
data = generator.normal(shape=(4, 3))

data

2024-07-03 12:58:23.973047: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ],
       [-0.57166284,  0.1480774 , -0.23362993]], dtype=float32)>

## Shuffle data

In [3]:
# shuffle the tensor using tf.random.shuffle()
shuffled_data = tf.random.shuffle(data, seed=None, name=None)

shuffled_data

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-1.2573844 , -0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702,  0.07595026],
       [ 0.09988727, -0.50998646, -0.7535805 ],
       [-0.57166284,  0.1480774 , -0.23362993]], dtype=float32)>

### Understanding the seed argument passed to tf.random.shuffle()

In [10]:
seed = tf.random.set_seed(42)

# shuffled_data_seed = tf.random.shuffle(data, seed=42)

shuffled_data_seed = tf.random.shuffle(data, seed=seed)

shuffled_data_seed

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.57166284,  0.1480774 , -0.23362993],
       [-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

> Rule 4: If we want out shuffled tensors to be in the same order, we have to use the global level random seed as well as the operation level seed