<a href="https://colab.research.google.com/github/kayc0des/TensorFlow_for_DeepLearning/blob/main/00-tf_fundamentals%20/00_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, we are going to cover some of the most basic fundamental concepts of tensors using TensorFlow

Outline:
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & Numpy
- Using @tf.function
- Using GPUs with TensorFlow (or TPUs)
- Exercises


# Introduction to Tensors

In this notebook we will be creating tensors using TensorFlow's tf.constant function.

- tf.constant(): Creates a constant tensor from a tensor-like object.

[Documentation](https://www.tensorflow.org/api_docs/python/tf/constant)

In [1]:
 # Import libraries

import tensorflow as tf

print(tf.__version__)

2.15.0


## Creating tensors with tf.constant()

A Scalar is a single Number

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor
scalar.ndim

0

A vector is a number with direction (e.g wind speed and direction)

In [4]:
# Create a vector
vector = tf.constant([10,
                      10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check Dimension of a vector
vector.ndim

1

A matrix is a 2-dimensional array of numbers

In [6]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check Dimension of matrix
matrix.ndim

2

In [10]:
# Create another matrix

another_matrix = tf.constant([[2, 5],
                              [4, 5],
                              [5, 2]], dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 5.],
       [4., 5.],
       [5., 2.]], dtype=float16)>

In [11]:
# Check Dimension
another_matrix.ndim

2

A Tensor is an n dimensional array of numbers where n can be any number.

- n = 0: Scalar

- n = 1: Vector

- n = 2: Matrix

- n >= 3: 3 to n dimensional array

In [15]:
# Let's create a tensor

tensor = tf.constant([[[1, 3, 5, 6],
                       [6, 8, 4, 7]],
                       [[6, 0, 4, 7],
                       [6, 8, 0, 7]],
                       [[8, 3, 5, 3],
                        [9, 7, 4, 2]]])

tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[1, 3, 5, 6],
        [6, 8, 4, 7]],

       [[6, 0, 4, 7],
        [6, 8, 0, 7]],

       [[8, 3, 5, 3],
        [9, 7, 4, 2]]], dtype=int32)>

In [14]:
tensor.ndim

3